### ISSUE TITLE
Roadmap: 3.0 😎

### ISSUE THREAD

**Issue by zkat** [zkat/miette#45]
This is the roadmap of major or breaking changes that are meant to land with `miette@3.0.0`. Is there anything you'd like to see here? Feel free to [start a discussion](https://github.com/zkat/miette/discussions/new) about it (under "ideas").

Probably breaking changes:

* [x] #47
* [x] https://github.com/zkat/miette/issues/34
* [x] #50
* [x] https://github.com/zkat/miette/issues/25
* [x] #63

Stuff that can probably land sooner, but should be in by 3.0:

* [x] https://github.com/zkat/miette/issues/49
* [x] https://github.com/zkat/miette/issues/43
* [x] https://github.com/zkat/miette/issues/22
* [x] https://github.com/zkat/miette/issues/4
* [x] #51
* [x] https://github.com/zkat/miette/issues/65

Stuff we need to remember to do right before tagging the release:

* [x] #57
* [x] #58
* [x] #59

**Comment by zkat** [comment]
For those following along: I just released miette@3.0.0-alpha.0 so you can try the changes so far!
